
[workspace]
members = [
    ".",
    "vendor/go2rust_stdlib_stubs",
    "vendor/go_ast",
    "vendor/go_token",
    "vendor/go_types",
    "vendor/internal_buildcfg",
    "vendor/internal_goexperiment",
    "vendor/internal_types_errors",
    "vendor/slices",
]

[package]
name = "source_stdlib_go_types_new_type_name"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "source_stdlib_go_types_new_type_name"
path = "main.rs"

[dependencies]
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
go_ast = { path = "vendor/go_ast" }
go_token = { path = "vendor/go_token" }
go_types = { path = "vendor/go_types" }
internal_buildcfg = { path = "vendor/internal_buildcfg" }
internal_goexperiment = { path = "vendor/internal_goexperiment" }
internal_types_errors = { path = "vendor/internal_types_errors" }
slices = { path = "vendor/slices" }
