
[workspace]
members = [
    ".",
    "vendor/example_com_atomicdep_dep",
    "vendor/go2rust_stdlib_stubs",
]

[package]
name = "external_atomic_int32_add"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "external_atomic_int32_add"
path = "main.rs"

[dependencies]
example_com_atomicdep_dep = { path = "vendor/example_com_atomicdep_dep" }
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
