
[workspace]
members = [
    ".",
    "vendor/go2rust_stdlib_stubs",
    "vendor/internal_abi",
    "vendor/internal_race",
    "vendor/internal_sync",
    "vendor/io",
    "vendor/sync",
    "vendor/sync_atomic",
]

[package]
name = "external_stdlib_variadic"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "external_stdlib_variadic"
path = "main.rs"

[dependencies]
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
internal_abi = { path = "vendor/internal_abi" }
internal_race = { path = "vendor/internal_race" }
internal_sync = { path = "vendor/internal_sync" }
io = { path = "vendor/io" }
sync = { path = "vendor/sync" }
sync_atomic = { path = "vendor/sync_atomic" }
