
[workspace]
members = [
    ".",
    "vendor/go2rust_stdlib_stubs",
    "vendor/go_ast",
    "vendor/go_token",
    "vendor/unicode",
    "vendor/unicode_utf8",
]

[package]
name = "source_stdlib_go_ast_walk_call_expr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "source_stdlib_go_ast_walk_call_expr"
path = "main.rs"

[dependencies]
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
go_ast = { path = "vendor/go_ast" }
go_token = { path = "vendor/go_token" }
unicode = { path = "vendor/unicode" }
unicode_utf8 = { path = "vendor/unicode_utf8" }
