
[workspace]
members = [
    ".",
    "vendor/bytes",
    "vendor/go2rust_stdlib_stubs",
    "vendor/internal_abi",
    "vendor/internal_bytealg",
    "vendor/internal_cpu",
    "vendor/internal_race",
    "vendor/internal_sync",
    "vendor/io",
    "vendor/iter",
    "vendor/math_bits",
    "vendor/sync",
    "vendor/sync_atomic",
    "vendor/unicode",
    "vendor/unicode_utf8",
]

[package]
name = "source_stdlib_io_copy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "source_stdlib_io_copy"
path = "main.rs"

[dependencies]
bytes = { path = "vendor/bytes" }
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
internal_abi = { path = "vendor/internal_abi" }
internal_bytealg = { path = "vendor/internal_bytealg" }
internal_cpu = { path = "vendor/internal_cpu" }
internal_race = { path = "vendor/internal_race" }
internal_sync = { path = "vendor/internal_sync" }
io = { path = "vendor/io" }
iter = { path = "vendor/iter" }
math_bits = { path = "vendor/math_bits" }
sync = { path = "vendor/sync" }
sync_atomic = { path = "vendor/sync_atomic" }
unicode = { path = "vendor/unicode" }
unicode_utf8 = { path = "vendor/unicode_utf8" }
