
[workspace]
members = [
    ".",
    "vendor/example_com_stringconst_dep",
    "vendor/go2rust_stdlib_stubs",
]

[package]
name = "package_string_const_concat_arg"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "package_string_const_concat_arg"
path = "main.rs"

[dependencies]
example_com_stringconst_dep = { path = "vendor/example_com_stringconst_dep" }
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
