
[workspace]
members = [
    ".",
    "vendor/go2rust_stdlib_stubs",
    "vendor/go_token",
]

[package]
name = "external_named_integer_conversion"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "external_named_integer_conversion"
path = "main.rs"

[dependencies]
go2rust_stdlib_stubs = { path = "vendor/go2rust_stdlib_stubs" }
go_token = { path = "vendor/go_token" }
