name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Please run 'gofmt -w .'"
            gofmt -d .
            exit 1
          fi

      - name: Run go vet
        run: |
          # Vet main package only, skip tests directory
          # (test files have multiple main functions for transpilation testing)
          go vet .

      - name: Build
        run: go build -o go2rust ./go

      - name: Setup BATS
        uses: bats-core/bats-action@3.0.0

      - name: Run tests
        run: ./test.sh

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "ERROR: Tests modified tracked files!"
            echo "Files changed:"
            git diff --name-only
            echo ""
            echo "Diff content:"
            git diff
            echo ""
            echo "This usually means:"
            echo "1. XFAIL tests were auto-promoted (moved from tests/XFAIL/ to tests/)"
            echo "2. Generated .rs files were updated"
            echo "3. Test configuration files were modified"
            echo ""
            echo "Please run tests locally and commit the changes if they are correct."
            exit 1
          fi
