name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Please run 'gofmt -w .'"
            gofmt -d .
            exit 1
          fi

      - name: Run go vet
        run: |
          # Vet main package only, skip tests directory
          # (test files have multiple main functions for transpilation testing)
          go vet .

      - name: Build
        run: go build -o go2rust .

      - name: Setup BATS
        uses: bats-core/bats-action@3.0.0

      - name: Run tests
        run: ./test.sh

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "ERROR: Tests modified tracked files!"
            echo "Please run tests locally and commit the changes:"
            git diff --name-only
            exit 1
          fi
